### ISSUE TITLE
apache default config

### ISSUE THREAD

**Issue by cavebeat** [chrisiaut/pictshare#6]
hi
default config for the engine https://github.com/chrisiaut/pictshare#on-nginx is available, the same for apache would be nice to have. 
best regards

**Comment by RavenNull** [comment]
My config file for Apache is as follows

`<VirtualHost *:80 *:443>
        ServerAdmin webmaster@localhost
	ServerName [whatever you want]
	ServerAlias [whatever your domain or subdomain is]
        DocumentRoot /var/www/whereveryouputit
        #This is sort of important because your site will be broken without the following 
	<Directory /var/www/whereveryouputit>
		Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
	</Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        LogLevel warn

        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost`

And the .htaccess file included will take care of the rest. This is assuming you are using SSL and that is being handled by a default-ssl.conf because you are lazy and have a wildcard SSL cert. If that isn't the case then you might need to configure it a little differently.

**Comment by chrisiaut** [comment]
@RavenNull you can create a pull request for the REAME.md file and add your config
